namespace Scalesoft.DisplayTool.Renderer.Widgets.WidgetUtils;

/// <summary>
///     List of all supported icons in Display tool
///     Every icon listed here should have Razor svg counterpart responsible for rendering
/// </summary>
public enum SupportedIcons
{
    CircleInfo,
    TriangleExclamation,
    CircleExclamation,
    ChevronUp,
    SquaredPlus,
    TooltipInfo,
    Check,
    Cross,
    Trash,
    ClockRotateLeft,
    CircleQuestion,
    Gear,
    CircleUser,
    CaretDown,
    StackedChevronUp,
    StackedChevronDown,
    FaceSmile,
    FaceFrown,
    PenToSquare,
    Wrench,
    SquareXMark,
    Bug,
    Registered,
    PenRuler,
    File,
    CollapseTriangle,
    Truck,
    Star,
    ClipboardList,
    LocationDot,
    EnvelopeOpenText,
    ThumbsDown,
    PenNib,
    ListUl,
    ChartLine,
    CircleXMark,
    CircleMinus,
    Spinner,
    ChartGantt,
    UserXMark,
    CirclePause,
    CircleNotch,
    Pencil,
    Lightbulb,
    FileLines,
    MagnifyingGlass,
    Shield,
    CircleStop,
    FileCircleQuestion,
    StarHalfStroke,
    HourglassHalf,
    MildCircles,
    ModerateCircles,
    SevereCircles,
    MagnifyingGlassCheck,
    StarSlash,
    ShieldXMark,
    CalendarDays,
    UserCheck,
    UserQuestion,
    UserExclamation,
    HighPyramid,
    MediumPyramid,
    LowPyramid,
    HandXMark,
    Calendar,
    FileHand,
}