using System.Xml.Serialization;
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

namespace Scalesoft.DisplayTool.Renderer.Clients.CdaValidator.Contracts;
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class detailedResult
{
    private DocumentValidXSD documentValidXSDField;

    private DocumentWellFormed documentWellFormedField;

    private MDAValidation mDAValidationField;

    private ValidationResultsOverview validationResultsOverviewField;

    private object itemField;

    /// <remarks/>
    public DocumentValidXSD DocumentValidXSD
    {
        get { return this.documentValidXSDField; }
        set { this.documentValidXSDField = value; }
    }

    /// <remarks/>
    public DocumentWellFormed DocumentWellFormed
    {
        get { return this.documentWellFormedField; }
        set { this.documentWellFormedField = value; }
    }

    /// <remarks/>
    public MDAValidation MDAValidation
    {
        get { return this.mDAValidationField; }
        set { this.mDAValidationField = value; }
    }

    /// <remarks/>
    public ValidationResultsOverview ValidationResultsOverview
    {
        get { return this.validationResultsOverviewField; }
        set { this.validationResultsOverviewField = value; }
    }

    /// <remarks/>
    [XmlElement("TemplateDesc", typeof(TemplateDesc))]
    [XmlElement("nistValidation", typeof(nistValidation))]
    public object Item
    {
        get { return this.itemField; }
        set { this.itemField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class DocumentValidXSD
{
    private XSDMessage[] xSDMessageField;

    private string resultField;

    private string nbOfErrorsField;

    private string nbOfWarningsField;

    /// <remarks/>
    [XmlElement("XSDMessage")]
    public XSDMessage[] XSDMessage
    {
        get { return this.xSDMessageField; }
        set { this.xSDMessageField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Result
    {
        get { return this.resultField; }
        set { this.resultField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "integer")]
    public string nbOfErrors
    {
        get { return this.nbOfErrorsField; }
        set { this.nbOfErrorsField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "integer")]
    public string nbOfWarnings
    {
        get { return this.nbOfWarningsField; }
        set { this.nbOfWarningsField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class XSDMessage
{
    private string severityField;

    private string messageField;

    private string columnNumberField;

    private string lineNumberField;

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Severity
    {
        get { return this.severityField; }
        set { this.severityField = value; }
    }

    /// <remarks/>
    public string Message
    {
        get { return this.messageField; }
        set { this.messageField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "integer")]
    public string columnNumber
    {
        get { return this.columnNumberField; }
        set { this.columnNumberField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "integer")]
    public string lineNumber
    {
        get { return this.lineNumberField; }
        set { this.lineNumberField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class DocumentWellFormed
{
    private string resultField;

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Result
    {
        get { return this.resultField; }
        set { this.resultField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class MDAValidation
{
    private object[] itemsField;

    private string resultField;

    /// <remarks/>
    [XmlElement("Error", typeof(Error))]
    [XmlElement("Info", typeof(Info))]
    [XmlElement("Note", typeof(Note))]
    [XmlElement("Warning", typeof(Warning))]
    public object[] Items
    {
        get { return this.itemsField; }
        set { this.itemsField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Result
    {
        get { return this.resultField; }
        set { this.resultField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class Error
{
    private string testField;

    private string locationField;

    private string descriptionField;

    private string identifiantField;

    private assertion assertionField;

    private string typeField;

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Test
    {
        get { return this.testField; }
        set { this.testField = value; }
    }

    /// <remarks/>
    public string Location
    {
        get { return this.locationField; }
        set { this.locationField = value; }
    }

    /// <remarks/>
    public string Description
    {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Identifiant
    {
        get { return this.identifiantField; }
        set { this.identifiantField = value; }
    }

    /// <remarks/>
    public assertion assertion
    {
        get { return this.assertionField; }
        set { this.assertionField = value; }
    }

    public string Type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class assertion
{
    private string assertionIdField;

    private string idSchemeField;

    /// <remarks/>
    [XmlAttribute(DataType = "anyURI")]
    public string assertionId
    {
        get { return this.assertionIdField; }
        set { this.assertionIdField = value; }
    }

    /// <remarks/>
    [XmlAttribute(DataType = "NCName")]
    public string idScheme
    {
        get { return this.idSchemeField; }
        set { this.idSchemeField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class Info
{
    private string testField;

    private string locationField;

    private string descriptionField;

    private string identifiantField;

    private assertion assertionField;

    private string typeField;

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Test
    {
        get { return this.testField; }
        set { this.testField = value; }
    }

    /// <remarks/>
    public string Location
    {
        get { return this.locationField; }
        set { this.locationField = value; }
    }

    /// <remarks/>
    public string Description
    {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Identifiant
    {
        get { return this.identifiantField; }
        set { this.identifiantField = value; }
    }

    /// <remarks/>
    public assertion assertion
    {
        get { return this.assertionField; }
        set { this.assertionField = value; }
    }

    public string Type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class Note
{
    private string testField;

    private string locationField;

    private string descriptionField;

    private string identifiantField;

    private assertion[] assertionField;

    private string typeField;

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Test
    {
        get { return this.testField; }
        set { this.testField = value; }
    }

    /// <remarks/>
    public string Location
    {
        get { return this.locationField; }
        set { this.locationField = value; }
    }

    /// <remarks/>
    public string Description
    {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Identifiant
    {
        get { return this.identifiantField; }
        set { this.identifiantField = value; }
    }

    /// <remarks/>
    [XmlElement("assertion")]
    public assertion[] assertion
    {
        get { return this.assertionField; }
        set { this.assertionField = value; }
    }

    public string Type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class Warning
{
    private string testField;

    private string locationField;

    private string descriptionField;

    private string identifiantField;

    private assertion assertionField;

    private string typeField;

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Test
    {
        get { return this.testField; }
        set { this.testField = value; }
    }

    /// <remarks/>
    public string Location
    {
        get { return this.locationField; }
        set { this.locationField = value; }
    }

    /// <remarks/>
    public string Description
    {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string Identifiant
    {
        get { return this.identifiantField; }
        set { this.identifiantField = value; }
    }

    /// <remarks/>
    public assertion assertion
    {
        get { return this.assertionField; }
        set { this.assertionField = value; }
    }

    public string Type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class ValidationResultsOverview
{
    private string validationDateField;

    private System.DateTime validationTimeField;

    private string validationServiceNameField;

    private string validationEngineField;

    private string validationTestResultField;

    private string validationServiceVersionField;

    /// <remarks/>
    public string ValidationDate
    {
        get { return this.validationDateField; }
        set { this.validationDateField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "time")]
    public System.DateTime ValidationTime
    {
        get { return this.validationTimeField; }
        set { this.validationTimeField = value; }
    }

    /// <remarks/>
    public string ValidationServiceName
    {
        get { return this.validationServiceNameField; }
        set { this.validationServiceNameField = value; }
    }

    /// <remarks/>
    public string ValidationEngine
    {
        get { return this.validationEngineField; }
        set { this.validationEngineField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NCName")]
    public string ValidationTestResult
    {
        get { return this.validationTestResultField; }
        set { this.validationTestResultField = value; }
    }

    /// <remarks/>
    [XmlElement(DataType = "NMTOKEN")]
    public string ValidationServiceVersion
    {
        get { return this.validationServiceVersionField; }
        set { this.validationServiceVersionField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class TemplateDesc
{
    private Template templateField;

    private string validationField;

    /// <remarks/>
    public Template Template
    {
        get { return this.templateField; }
        set { this.templateField = value; }
    }

    /// <remarks/>
    [XmlAttribute(DataType = "NCName")]
    public string validation
    {
        get { return this.validationField; }
        set { this.validationField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class Template
{
    private object[] itemsField;

    private string locationField;

    private string typeField;

    private string validationField;

    /// <remarks/>
    [XmlElement("Template", typeof(Template))]
    [XmlElement("templateId", typeof(templateId))]
    public object[] Items
    {
        get { return this.itemsField; }
        set { this.itemsField = value; }
    }

    /// <remarks/>
    [XmlAttribute()]
    public string location
    {
        get { return this.locationField; }
        set { this.locationField = value; }
    }

    /// <remarks/>
    [XmlAttribute(DataType = "NCName")]
    public string type
    {
        get { return this.typeField; }
        set { this.typeField = value; }
    }

    /// <remarks/>
    [XmlAttribute(DataType = "NCName")]
    public string validation
    {
        get { return this.validationField; }
        set { this.validationField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class templateId
{
    private string idField;

    private string nameField;

    /// <remarks/>
    [XmlAttribute(DataType = "NMTOKEN")]
    public string id
    {
        get { return this.idField; }
        set { this.idField = value; }
    }

    /// <remarks/>
    [XmlAttribute()]
    public string name
    {
        get { return this.nameField; }
        set { this.nameField = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType = true)]
[XmlRoot(Namespace = "", IsNullable = false)]
public partial class nistValidation
{
    private string nistVersionField;

    /// <remarks/>
    [XmlAttribute()]
    public string nistVersion
    {
        get { return this.nistVersionField; }
        set { this.nistVersionField = value; }
    }
}