//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
namespace Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net")]
    public partial class SOAPException
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", ConfigurationName="Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidation" +
        "WS")]
    public interface ModelBasedValidationWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypesResponse> getListSupportedMediaTypesAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.SOAPException), Action="", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocumentResponse> validateDocumentAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.aboutResponse> aboutAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.about request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.SOAPException), Action="", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidatorsResponse> getListOfValidatorsAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidators request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.SOAPException), Action="", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64DocumentResponse> validateBase64DocumentAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64Document request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.SOAPException), Action="", Name="SOAPException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64DocumentResponse> validateB64DocumentAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64Document request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListSupportedMediaTypes", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class getListSupportedMediaTypes
    {
        
        public getListSupportedMediaTypes()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListSupportedMediaTypesResponse", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class getListSupportedMediaTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getListSupportedMediaTypesResponse()
        {
        }
        
        public getListSupportedMediaTypesResponse(string[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDocument", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class validateDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validator;
        
        public validateDocument()
        {
        }
        
        public validateDocument(string document, string validator)
        {
            this.document = document;
            this.validator = validator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDocumentResponse", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class validateDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailedResult;
        
        public validateDocumentResponse()
        {
        }
        
        public validateDocumentResponse(string DetailedResult)
        {
            this.DetailedResult = DetailedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="about", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class about
    {
        
        public about()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="aboutResponse", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class aboutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string about;
        
        public aboutResponse()
        {
        }
        
        public aboutResponse(string about)
        {
            this.about = about;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfValidators", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class getListOfValidators
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descriminator;
        
        public getListOfValidators()
        {
        }
        
        public getListOfValidators(string descriminator)
        {
            this.descriminator = descriminator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListOfValidatorsResponse", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class getListOfValidatorsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Validators", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Validators;
        
        public getListOfValidatorsResponse()
        {
        }
        
        public getListOfValidatorsResponse(string[] Validators)
        {
            this.Validators = Validators;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateBase64Document", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class validateBase64Document
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string base64Document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validator;
        
        public validateBase64Document()
        {
        }
        
        public validateBase64Document(string base64Document, string validator)
        {
            this.base64Document = base64Document;
            this.validator = validator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateBase64DocumentResponse", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class validateBase64DocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailedResult;
        
        public validateBase64DocumentResponse()
        {
        }
        
        public validateBase64DocumentResponse(string DetailedResult)
        {
            this.DetailedResult = DetailedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateB64Document", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class validateB64Document
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string base64Document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultMediaType;
        
        public validateB64Document()
        {
        }
        
        public validateB64Document(string base64Document, string validator, string resultMediaType)
        {
            this.base64Document = base64Document;
            this.validator = validator;
            this.resultMediaType = resultMediaType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateB64DocumentResponse", WrapperNamespace="http://ws.mb.validator.gazelle.ihe.net", IsWrapped=true)]
    public partial class validateB64DocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.mb.validator.gazelle.ihe.net", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DetailedResult;
        
        public validateB64DocumentResponse()
        {
        }
        
        public validateB64DocumentResponse(string DetailedResult)
        {
            this.DetailedResult = DetailedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ModelBasedValidationWSChannel : Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ModelBasedValidationWSClient : System.ServiceModel.ClientBase<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS>, Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ModelBasedValidationWSClient() : 
                base(ModelBasedValidationWSClient.GetDefaultBinding(), ModelBasedValidationWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ModelBasedValidationWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ModelBasedValidationWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ModelBasedValidationWSClient.GetBindingForEndpoint(endpointConfiguration), ModelBasedValidationWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ModelBasedValidationWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ModelBasedValidationWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ModelBasedValidationWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ModelBasedValidationWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ModelBasedValidationWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypesResponse> Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS.getListSupportedMediaTypesAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypes request)
        {
            return base.Channel.getListSupportedMediaTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypesResponse> getListSupportedMediaTypesAsync()
        {
            Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypes inValue = new Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListSupportedMediaTypes();
            return ((Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS)(this)).getListSupportedMediaTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocumentResponse> Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS.validateDocumentAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocument request)
        {
            return base.Channel.validateDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocumentResponse> validateDocumentAsync(string document, string validator)
        {
            Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocument inValue = new Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateDocument();
            inValue.document = document;
            inValue.validator = validator;
            return ((Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS)(this)).validateDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.aboutResponse> Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS.aboutAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.about request)
        {
            return base.Channel.aboutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.aboutResponse> aboutAsync()
        {
            Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.about inValue = new Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.about();
            return ((Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS)(this)).aboutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidatorsResponse> Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS.getListOfValidatorsAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidators request)
        {
            return base.Channel.getListOfValidatorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidatorsResponse> getListOfValidatorsAsync(string descriminator)
        {
            Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidators inValue = new Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.getListOfValidators();
            inValue.descriminator = descriminator;
            return ((Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS)(this)).getListOfValidatorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64DocumentResponse> Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS.validateBase64DocumentAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64Document request)
        {
            return base.Channel.validateBase64DocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64DocumentResponse> validateBase64DocumentAsync(string base64Document, string validator)
        {
            Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64Document inValue = new Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateBase64Document();
            inValue.base64Document = base64Document;
            inValue.validator = validator;
            return ((Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS)(this)).validateBase64DocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64DocumentResponse> Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS.validateB64DocumentAsync(Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64Document request)
        {
            return base.Channel.validateB64DocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64DocumentResponse> validateB64DocumentAsync(string base64Document, string validator, string resultMediaType)
        {
            Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64Document inValue = new Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.validateB64Document();
            inValue.base64Document = base64Document;
            inValue.validator = validator;
            inValue.resultMediaType = resultMediaType;
            return ((Scalesoft.DisplayTool.Renderer.ModelBasedValidationWSService.ModelBasedValidationWS)(this)).validateB64DocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ModelBasedValidationWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ModelBasedValidationWSPort))
            {
                return new System.ServiceModel.EndpointAddress("https://gazelle.ehdsi.eu/CDAGenerator-ejb/ModelBasedValidationWSService/ModelBase" +
                        "dValidationWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ModelBasedValidationWSClient.GetBindingForEndpoint(EndpointConfiguration.ModelBasedValidationWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ModelBasedValidationWSClient.GetEndpointAddress(EndpointConfiguration.ModelBasedValidationWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ModelBasedValidationWSPort,
        }
    }
}
